apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-r2xr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-prmu-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-r2xr@sha256:15c1bde48c1231296c17c865c1937575c8f0938eb298c57660e8ca2028060dad
        name: my-go
        resources: {}
status: {}
